(import (chicken process-context); for command-line-arguments
        (chicken io); for read-line
        (chicken file))

;;; Tokenize
(define (tokenize str)
  (define (subst-unit lst)
    (define (subst ls) (if (string=? "[]" (list->string ls)) unit ls))
    (map subst lst))
  (subst-symbol (subst-unit (split-w/sp (string->list str)))))
(define (obj? lst) (and (pair? lst) (symbol? (car lst))))
(define (subst-symbol lists)
  (define (list->symbol lst) (string->symbol (list->string lst)))
  (map (lambda (lst) (if (obj? lst) lst (list->symbol lst))) lists))
(define (filter pred lst)
  (foldr (lambda (x y) (if (pred x) (cons x y) y)) '() lst))
(define (split-w/sp lst)
  (split-w/ char-whitespace? lst))
(define (split-w/ pred lst)
  (filter (lambda (x) (not (null? x)))
    (let loop ((lst lst) (cur '()) (buf '()))
      (cond ((null? lst) (reverse (cons (reverse cur) buf)))
            ((pred (car lst))
             (loop (cdr lst) '() (cons (reverse cur) buf)))
            (else (loop (cdr lst) (cons (car lst) cur) buf))))))

;;; Parse
(define (parse tokens arities)
  (define (parse-n n tokens)
    (cond ((= n 0) (cons '() tokens))
          ((null? tokens)
           (cons (err "Unexpected end of tokens") tokens))
          (else (let* ((first (parse-one tokens))
                       (rest (parse-n (- n 1) (cdr first))))
                  (cons (cons (car first) (car rest)) (cdr rest))))))
  (define (parse-one tokens)
    (cond ((null? tokens)
           (cons (err "Unexpected end of tokens") tokens))
          ((err? tokens) tokens)
          (else (let* ((token (car tokens))
                       (arity (assq token arities)))
                  (if arity
                    (let ((result (parse-n (cdr arity) (cdr tokens))))
                      (cons (cons token (car result)) (cdr result)))
                    tokens)))))
  (define (remove-comment tokens)
    (cond ((null? tokens) tokens)
          ((eq? (car tokens) '/*)
           (let ((x (or (memq '*/ (cdr tokens)) '())))
             (remove-comment (if (null? x) x (cdr x)))))
          ((eq? (car tokens) '*/) (err "Unexpected end of comment"))
          (else (let ((rest (remove-comment (cdr tokens))))
                  (if (err? rest) rest (cons (car tokens) rest))))))
  (let* ((tokens (remove-comment tokens)) (r (parse-one tokens)))
    (if (null? (cdr r)) (car r) (err "Unexpected tokens"))))

;;; Macro
(define (expand-macro ast macro-list)
  (define (map-ast f ast)
    (if (and (not (null? ast)) (list? ast))
        (f (cons (car ast) (map (lambda (x) (map-ast f x)) (cdr ast))))
        ast))
  (define (map-tree f tr)
    (if (list? tr) (map (lambda (x) (map-tree f x)) tr) (f tr)))
  (define (subst-tree tr bindings)
    (map-tree (lambda (x) (let ((binding (assq x bindings)))
                            (if binding (cdr binding) x))) tr))
  (let expand ((ast ast))
    (cond ((and (not (null? ast)) (list? ast))
           (let ((macro (assq (car ast) macro-list)))
             (if macro
               (let* ((params (cadr macro))
                      (subst (caddr macro))
                      (args (map expand (cdr ast))))
                 (subst-tree (map-ast expand subst)
                             (map cons params args)))
               (cons (car ast) (map expand (cdr ast))))))
          (else ast))))

;;; Values
(define (tagged? x tag) (and (pair? x) (eq? (car x) tag)))
; Proc
(define (make-closure x body env) (list 'closure x body env))
(define (proc? obj) (or (tagged? obj 'primitive) (tagged? obj 'closure)))
(define (closure-env proc) (cadddr proc))
; Unit
(define unit '(unit))
(define (unit? obj) (and (tagged? obj 'unit) (null? (cdr obj))))
; Symbol
(define (make-sym obj) (if (symbol? obj)
                         (cons 'symbol obj)
                         (err (list "make-sym: not a symbol" obj))))
(define (sym? obj) (and (tagged? obj 'symbol) (symbol? (cdr obj))))
(define (sym-content obj) (if (sym? obj) (cdr obj) unit))
; Error
(define (err err-data) (cons 'error err-data))
(define (err? data) (tagged? data 'error))
; Action
(define (action? obj) (tagged? obj 'action))

;;; Store
(define chunk-size 65536)
(define free-marker 'free)
(define (make-store locs stack heap) (list locs stack heap))
(define (free-locs rt) (car rt))
(define (runtime-stack rt) (cadr rt))
(define (runtime-heap rt) (caddr rt))
(define (heap-length rt) (vector-length (runtime-heap rt)))
(define (set-free-locs! rt lst) (set-car! rt lst))
(define (heap-update! rt new) (set-car! (cddr rt) new))
(define (extend-store! rt); -> unspecified
  (let* ((old (runtime-heap rt))
         (n (heap-length rt))
         (new (make-vector (* 2 n) free-marker)))
    (let loop ((i 0))
      (if (< i n) (begin (vector-set! new i (vector-ref old i))
                         (loop (+ i 1)))))
    (heap-update! rt new)
    (set-free-locs! rt (range n (+ chunk-size n)))))
(define (range n m)
  (let loop ((m m) (lst '()))
    (if (= n m) lst (loop (- m 1) (cons (- m 1) lst)))))
(define (make-empty-store)
  (make-store (range 0 chunk-size)
              '()
              (make-vector chunk-size free-marker)))
(define (allocate! rt val); -> loc
;; for GC test
;  (push-obj! rt val)
;  (gc! rt)
;  (pop-obj! rt)
  (if (null? (free-locs rt))
    (begin (push-obj! rt val)
           (gc! rt)
           (pop-obj! rt)
           (if (null? (free-locs rt)) (extend-store! rt))))
  (let ((loc (car (free-locs rt))))
    (vector-set! (runtime-heap rt) loc val)
    (set-free-locs! rt (cdr (free-locs rt)))
    loc))
(define (resolve rt loc); -> val
  (if (err? loc) loc
    (let ((val (vector-ref (runtime-heap rt) loc)))
      (if (eq? val free-marker)
        (err (list "Invalid location:" loc))
        val))))
(define (update! rt loc val); -> unspecified
  (if (err? loc)
    (err (cons "Update variable unbound: " (cdr loc)))
    (begin (vector-set! (runtime-heap rt) loc val) #f)))

;;; Environment
(define (empty-env? env) (null? env))
(define (make-frame bindings parent) (list 'frame bindings parent))
(define (frame? obj) (tagged? obj 'frame))
(define (frame-bindings frame) (cadr frame))
(define (frame-parent frame) (caddr frame))
(define (add-binding var loc frame)
  (make-frame (cons (cons var loc) (frame-bindings frame))
              (frame-parent frame)))
(define (extend-env! var loc env rt)
  (allocate! rt (make-frame (list (cons var loc)) env)))
(define (lookup rt var env)
  (if (empty-env? env)
    (err (list 'Unbound var))
    (let ((frame (resolve rt env)))
      (cond ((err? frame) frame)
            ((not (frame? frame)) (err (list "Not a frame:" frame)))
            (else (let ((binding (assoc var (frame-bindings frame))))
                    (if binding
                      (cdr binding)
                      (lookup rt var (frame-parent frame)))))))))

;;; Garbage collection
(define (push-obj! rt obj)
  (set-car! (cdr rt) (cons obj (runtime-stack rt))))
(define (pop-obj! rt)
  (let ((obj (car (runtime-stack rt))) (rest (cdr (runtime-stack rt))))
    (set-car! (cdr rt) rest) obj))
(define (protect rt obj thunk)
  (push-obj! rt obj) (let ((result (thunk))) (pop-obj! rt) result))
(define (mark-locs rt)
  (let ((marks (make-vector (vector-length (runtime-heap rt)) #f)))
    (define (marked? loc) (vector-ref marks loc))
    (define (mark! loc) (vector-set! marks loc #t))
    (define (mark-loc! loc)
      (if (not (marked? loc))
        (begin (mark! loc) (mark-obj! (resolve rt loc)))))
    (define (mark-obj! obj)
      (cond ((integer? obj) (mark-loc! obj))
            ((tagged? obj 'closure) (mark-loc! (closure-env obj)))
            ((action? obj) (for-each mark-obj! (caddr obj)))
            ((primitive? obj) (for-each mark-obj! (cadddr obj)))
            ((frame? obj)
             (for-each (lambda (binding) (mark-loc! (cdr binding)))
                       (frame-bindings obj))
             (if (not (empty-env? (frame-parent obj)))
               (mark-loc! (frame-parent obj))))
            (else (trace-extra-obj! obj mark-obj!))))
    (mark-loc! global-env)
    (for-each mark-obj! (runtime-stack rt))
    marks))
(define gc-tracers '())
(define (register-gc-tracer! pred trace)
  (set! gc-tracers (cons (cons pred trace) gc-tracers)))
(define (trace-extra-obj! obj visit)
  (let loop ((tracers gc-tracers))
    (cond ((null? tracers) #f)
          (((caar tracers) obj) ((cdar tracers) obj visit) #t)
          (else (loop (cdr tracers))))))
(define (sweep! rt marks)
  (let* ((n (heap-length rt)))
    (let loop ((i 0) (free '()))
      (if (= i n)
        (set-free-locs! rt (reverse free))
        (if (vector-ref marks i)
          (loop (+ i 1) free)
          (begin (vector-set! (runtime-heap rt) i free-marker)
                 (loop (+ i 1) (cons i free))))))))
(define (gc! rt) (let ((marks (mark-locs rt))) (sweep! rt marks) rt))

;;; Evaluator
(define (analyze rt expr)
  (cond ((symbol? expr)
         (lambda (env) (resolve rt (lookup rt expr env))))
        ((null? expr) (lambda (env) (err "Invalid expression")))
        ((or (unit? expr) (err? expr)) (lambda (env) expr))
        ((eq? (car expr) 'sym)
         (if (symbol? (cadr expr))
           (lambda (env) (make-sym (cadr expr)))
           (lambda (env) (err "Invalid arg: sym"))))
        ((eq? (car expr) 'fn)
         (let ((body (analyze rt (caddr expr))))
           (lambda (env) (make-closure (cadr expr) body env))))
        ((eq? (car expr) 'if)
         (let ((condition (analyze-sub rt (cadr expr)))
               (true-clause (analyze-sub rt (caddr expr)))
               (false-clause (analyze-sub rt (cadddr expr))))
           (lambda (env)
             (let ((pred (condition env)))
               (cond ((err? pred) pred)
                     ((unit? pred) (false-clause env))
                     (else (true-clause env)))))))
        ((eq? (car expr) 'def)
         (let* ((var (cadr expr))
                (val-clause (analyze-sub rt (caddr expr)))
                (conti (analyze rt (cadddr expr))))
           (lambda (env)
             (let ((val (val-clause env)))
               (if (err? val) val
                 (let ((loc (allocate! rt val))
                       (frame (resolve rt env)))
                   (begin (update! rt
                                   env
                                   (add-binding var loc frame))
                          (conti env))))))))
        ((eq? (car expr) 'set)
         (let* ((var (cadr expr))
                (val-clause (analyze-sub rt (caddr expr)))
                (conti (analyze rt (cadddr expr))))
           (lambda (env)
             (let ((val (val-clause env)))
               (if (err? val) val
                 (let ((r (update! rt 
                                   (lookup rt (cadr expr) env)
                                   val)))
                   (if (err? r) r (conti env))))))))
        ((eq? (car expr) 'ap)
         (let ((proc-clause (analyze-sub rt (cadr expr)))
               (arg-clause (analyze-sub rt (caddr expr))))
           (lambda (env)
             (let* ((proc (proc-clause env))
                    (thunk (lambda () (ap rt proc (arg-clause env)))))
               (protect rt proc thunk)))))
        (else (lambda (env) (err (list "Invalid syntax: " expr))))))
(define (analyze-sub rt expr)
  (let ((analyzed (analyze rt expr)))
    (if (and (pair? expr) (eq? (car expr) 'def))
      (lambda (env)
        (let ((new-env (allocate! rt (make-frame '() env))))
          (protect rt new-env (lambda () (analyzed new-env)))))
      analyzed)))
(define (ev rt expr env)
  (protect rt env (lambda () ((analyze rt expr) env))))
(define (ap rt proc arg); -> val
  (cond ((err? proc) proc)
        ((err? arg) arg)
        ((tagged? proc 'primitive) (apply-primitive proc arg))
        ((tagged? proc 'closure)
         (let* ((loc (allocate! rt arg))
                (extended-env
                  (extend-env! (cadr proc) loc (closure-env proc) rt))
                (thunk (lambda () ((caddr proc) extended-env))))
           (protect rt extended-env thunk)))
        (else (err (list "Invalid application " proc)))))

;;; IO helpers
(define (file->string filename); This works for chicken only
  (handle-exceptions exn (err (list "Error: file->string " filename))
    (call-with-input-file filename
      (lambda (port) (read-string #f port)))))
(define (write-symbol filename sym)
  (define (write-sym port)
    (display (string-append (symbol->string (sym-content sym)) "\n") port))
  (handle-exceptions exn (err (list "Error: write-symbol" filename))
    (call-with-output-file filename write-sym #:append)))

;;; Encode
(define (string->encode rt str)
  (define (list->encode rt lst)
    (make-fn 2
      (lambda (f x)
        (let loop ((lst lst))
          (if (null? lst)
            x
            (let ((proc (ap rt f (car lst))))
              (protect rt proc (lambda ()
                                 (let ((arg (loop (cdr lst))))
                                   (ap rt proc arg))))))))))
  (if (string? str)
    (list->encode
      rt
      (map make-sym (subst-symbol (split-w/sp (string->list str)))))
    (err (list "string->encode: Not a string" str))))

;;; Actions
(define (action-dispatch rt act); -> val
  (define (action-write args)
    (let ((path (car args))
          (sym (cadr args)))
      (if (and (sym? path) (sym? sym))
        (let ((r (write-symbol (sym->string path) sym)))
          (if (err? r) r unit))
        (err (list "write: expected symbols")))))
  (define (action-read rt args)
    (let ((path-sym (car args)))
      (read-path path-sym
                 (lambda (s) (string->encode rt s))
                 (list "read: expected symbol"))))
  (define (action-run rt args)
    (define (read-path path f msg)
      (if (sym? path)
        (let ((str (file->string (sym->string path))))
          (if (err? str) str (f str)))
        (err msg)))
    (let ((path-sym (car args)))
      (define (run-source src) (run-src rt src))
      (read-path path-sym run-source (list "run: expected symbol"))))
  (define (sym->string sym) (symbol->string (cdr sym)))
  (define (action-print args)
    (let ((val (car args)))
      (display (if (sym? val) (sym->string val) val)) (newline) unit))
  (define (action-bind rt args)
    (let ((action (car args)) (proc (cadr args)))
      (if (not (proc? proc))
        (err (list "bind: not a proc" proc))
        (protect
          rt
          proc
          (lambda ()
            (let ((val (run-action rt action)))
              (if (err? val)
                val
                (let ((r (ap rt proc val)))
                  (if (err? r) r (run-action rt r))))))))))
  (let ((type (car act))
        (args (cadr act)))
    (cond ((eq? type 'print) (action-print args))
          ((eq? type 'read-stdin) (string->encode rt (read-line)))
          ((eq? type 'write) (action-write args))
          ((eq? type 'read) (action-read rt args))
          ((eq? type 'run) (action-run rt args))
          ((eq? type 'bind) (action-bind rt args))
          (else (additional-actions type args)))))
(define (err-unknown-action) (err "Unknown action"))
(define (additional-actions type args) (err-unknown-action))
(define (run-action rt value); -> val
  (cond ((err? value) value)
        ((tagged? value 'action) (action-dispatch rt (cdr value)))
        (else value)))

;;; Primitive constructors
(define (make-fn arity f)
  (if (= arity 0) (f) (list 'primitive f arity '())))
(define (primitive? obj) (tagged? obj 'primitive))
(define (apply-primitive prim arg)
  (let* ((f (cadr prim))
         (n (caddr prim))
         (args (cadddr prim))
         (new-args (cons arg args)))
    (if (= n 1)
        (apply f (reverse new-args))
        (list 'primitive f (- n 1) new-args))))
(define (make-pred pred) (make-fn 1 (lambda (x) (if (pred x) x unit))))
(define (make-action n name)
  (make-fn n (lambda args (list 'action name args))))
(define (sym-eq? x y)
  (if (and (sym? x) (sym? y) (eq? (sym-content x) (sym-content y)))
    x
    unit))

;;; Primitive values
(define primitives
  (list (cons 'proc? (make-pred proc?))
        (cons 'act? (make-pred action?))
        (cons 'sym? (make-pred sym?))
        (cons '//* (make-sym '/*))
        (cons '*// (make-sym '*/))
        (cons 'sym-eq? (make-fn 2 sym-eq?))
        (cons 'bind (make-action 2 'bind))
        (cons 'input (make-action 0 'read-stdin))
        (cons 'run (make-action 1 'run))
        (cons 'read (make-action 1 'read))
        (cons 'print (make-action 1 'print))
        (cons 'write (make-action 2 'write))))

(define (get-mucha-path-string)
  (let ((path (get-environment-variable "MUCHA_PATH")))
    (if path (string-append path "/") "./")))
(define (from-mucha-path str)
  (string-append (get-mucha-path-string) str))
(define (mucha-path)
  (make-sym (string->symbol (get-mucha-path-string))))

;;; Macro assignment
(define (parse-macro-source str)
  (let* ((tokens (tokenize str))
         (contents (split-w/bar tokens)))
    (make-pairs contents)))
(define (split-w/bar tokens)
  (split-w/ (lambda (x) (eq? x (string->symbol "|"))) tokens))
(define (make-pairs lst)
  (if (or (null? lst) (null? (cdr lst)))
    '()
    (cons (list (car lst) (cadr lst)) (make-pairs (cddr lst)))))
(define primitive-arities
  '((fn . 2) (ap . 2) (def . 3) (set . 3) (if . 3) (sym . 1)))

(define macro-file (from-mucha-path "boot/macros.mch"))
(define macro-source
  (let ((src (file->string macro-file)))
    (if (err? src)
      (begin (display (string-append  macro-file " not found\n")) '())
      (parse-macro-source src))))
(define macro-arities
  (map (lambda (m) (cons (caar m) (length (cdar m)))) macro-source))
(define arities (append primitive-arities macro-arities))
(define macros
  (map (lambda (m) (list (caar m) (cdar m) (parse (cadr m) arities)))
       macro-source))

;;; Runtime
(define (initialize-runtime)
  (define rt (make-empty-store))
  (allocate! rt (make-frame '() '()))
  rt)
;; for GC test
;  (vector-set! (runtime-heap rt) global-env (make-frame '() '()))
;  (set-free-locs! rt (cdr (free-locs rt)))
;  rt)

(define (run-src rt src)
  (define (make-ast src)
    (expand-macro (parse (tokenize src) arities) macros))
  (if (string? src)
    (run-action rt (ev rt (make-ast src) global-env))
    (err (list "run-src: Not a string" src))))
(define (bind-primitives! rt prims)
  (define (bind! binding)
    (let* ((loc (allocate! rt (cdr binding)))
           (frame (resolve rt global-env)))
      (update! rt global-env (add-binding (car binding) loc frame))))
  (for-each bind! prims))
(define (initialize!) (bind-primitives! runtime primitives))

;;; REPL
(define (repl rt) (display "> ")
                  (let ((str (read-line)))
                    (if (string=? str "exit")
                      (display "Bye-bye\n")
                      (let ((val (run-src rt str)))
                        (display (if (unit? val) "[]" val))
                        (newline)
                        (repl rt)))))

;;; Initialization ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(define global-env 0)
(define runtime (initialize-runtime))
(define (run filename) (run-src runtime (file->string filename)))
(define (main)
  (let ((arg-list (command-line-arguments)))
    (if (= (length arg-list) 1)
      (let ((result (run (car arg-list))))
        (if (err? result) (display result)))
      (begin (display "MUCHA") (newline) (repl runtime)))))
